[bot]
bot_admins = ["0", "0", "0"]
allowed_bots = ["204255221017214977"] # list of bots allowed to run commands
prefixes = ["c;", "c:"] # prefixes used in DMs
dm_webhook = "" # webhook to send DM messages to
blocked_users = ["0"] # users blocked from DMing the bot
log_webhook = "" # webhook to log errors to
# custom status
[bot.custom_status]
type = "listening" # <blank>, "listening", "playing", or "watching"
status = "c;help"
[auth]
token = 'secretDiscordString'
database_url = 'postgresql://starbot:starbot@localhost/starbot'
bolt_path = "bolt.db" # path to the Bolt databse, relative to current directory

[logging]
log_level = "DEBUG"
debug_url = ""
info_url = ""
warn_url = ""
error_url = ""
panic_url = ""